/**
 * Live integration check for the frontend service layer against a running
 * Django backend (node >=18). Run from front/:
 *   node scripts/integration-check.mjs
 */

// Minimal browser shims so the service modules load outside the browser.
const storage = new Map()
globalThis.localStorage = {
  getItem: (k) => (storage.has(k) ? storage.get(k) : null),
  setItem: (k, v) => storage.set(k, String(v)),
  removeItem: (k) => storage.delete(k),
}

const elementStub = () => ({
  appendChild() {},
  remove() {},
  setAttribute() {},
  style: {},
  classList: { add() {}, remove() {}, toggle() {} },
  addEventListener() {},
  querySelector: () => null,
  querySelectorAll: () => [],
})

globalThis.window = {
  addEventListener() {},
  dispatchEvent() {},
  matchMedia: () => ({ matches: false, addEventListener() {}, addListener() {} }),
}
globalThis.document = {
  createElement: elementStub,
  querySelector: () => null,
  querySelectorAll: () => [],
  addEventListener() {},
  readyState: 'complete',
  head: { appendChild() {} },
  body: { appendChild() {}, contains: () => true },
}

const { authService } = await import('../src/js/services/auth.js')
const { tripService } = await import('../src/js/services/trips.js')
const { apiFetch } = await import('../src/js/services/api.js')
const { timelineService } = await import('../src/js/services/timeline.js')
const { placeService } = await import('../src/js/services/places.js')
const { budgetService, getSpentOrFallback } = await import('../src/js/services/budget.js')
const { packingService } = await import('../src/js/services/packing.js')
const { weatherService } = await import('../src/js/services/weather.js')
const { notesService } = await import('../src/js/services/notes.js')
const { notificationsService } = await import('../src/js/services/notifications.js')

let failures = 0
function check(label, condition, extra = '') {
  const ok = Boolean(condition)
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${label}${ok ? '' : `  ${extra}`}`)
  if (!ok) failures += 1
}

const email = `int-check-${Date.now()}@example.com`
let created

try {
  // ---- Auth ----------------------------------------------------------
  const user = await authService.register({
    email,
    username: `chk${Date.now() % 100000}`,
    password: 'Integr-Check-1!',
    password_confirm: 'Integr-Check-1!',
  })
  check('register returns user', user && user.email === email)

  // ---- Trips ---------------------------------------------------------
  await tripService.ensureLoaded()
  const before = tripService.list().length
  check('trips list loaded from API', Array.isArray(tripService.list()))

  created = await tripService.create({
    title: 'تست یکپارچگی',
    destination: 'Rasht',
    startDate: new Date('2026-10-01T00:00:00'),
    endDate: new Date('2026-10-03T00:00:00'),
    travelers: 2,
    budget: { total: 1500000 },
  })
  check('create returns mapped trip', Boolean(created?.id))
  check(
    'days generated by backend',
    created._raw.days_count === 3 || created._raw.days?.length === 3,
    JSON.stringify(created._raw),
  )

  await tripService.reload()
  check('trip persists after reload', tripService.list().some((t) => t.id === created.id))
  check('list grew by one', tripService.list().length === before + 1)

  const dashboard = await apiFetch('/dashboard/')
  check('dashboard reachable with Bearer token', typeof dashboard.trips.total === 'number')

  // ---- Timeline / Places / drag & drop --------------------------------
  await timelineService.ensureLoaded(created.id)
  const days = timelineService.getDays({ id: created.id })
  check('days loaded from API', days.length === 3, `got ${days.length}`)

  const p1 = await placeService.create(created.id, { name: 'موزه آبی', category: 'museum' })
  const p2 = await placeService.create(created.id, { name: 'بازار', category: 'shopping' })
  check('places created with auto position', p1.order === 0 && p2.order === 1, `${p1.order},${p2.order}`)
  check('place findByName works', placeService.findByName(created.id, 'موزه آبی')?.id === p1.id)

  const day1 = days[0]
  await timelineService.addActivity(created.id, day1.id, {
    title: 'گشت صبح', time: '10:00', category: 'culture', cost: 0,
    durationMinutes: 90, notes: '',
  })
  await timelineService.addActivity(created.id, day1.id, {
    title: 'ناهار', time: '13:30', category: 'food', cost: 250000,
    durationMinutes: 60, notes: '',
  })

  let serverActivities = (await apiFetch(`/trips/${created.id}/activities/?page_size=100`)).results
  check('activities persisted via optimistic path', serverActivities.length === 2, `got ${serverActivities.length}`)

  const firstActivityId = day1.activities[0].id
  timelineService.toggleDone(created.id, day1.id, firstActivityId)
  await new Promise((r) => setTimeout(r, 200))
  const doneList = (await apiFetch(`/trips/${created.id}/activities/?completed=true&page_size=100`)).results
  check('toggle done persisted (PATCH completed)', doneList.length === 1)

  // Drag & drop: move "ناهار" into day 3 through the reorder endpoint.
  const moved = day1.activities.find((a) => a.title === 'ناهار')
  const day3 = days[2]
  day1.activities.splice(day1.activities.indexOf(moved), 1)
  day3.activities.push(moved)
  await apiFetch(`/trips/${created.id}/timeline/reorder/`, {
    method: 'PATCH',
    body: { kind: 'activities', day_id: day3.id, items: [{ id: moved.id, position: 0 }] },
  })

  const fresh = (await apiFetch(`/trips/${created.id}/activities/?page_size=100`)).results
  check('drag&drop survives refresh (day changed)', fresh.some((a) => a.id === moved.id && a.day === day3.id))

  // ---- Budget (Integration Test 06) -----------------------------------
  await budgetService.ensureLoaded(created.id)
  const spentBefore = getSpentOrFallback(tripService.getById(created.id))
  check('budget summary loaded', budgetService.getSummary(created.id)?.spent === 0)

  await budgetService.create({
    tripId: created.id,
    title: 'هتل',
    amount: 800000,
    category: 'accommodation',
  })
  const summaryAfter = budgetService.getSummary(created.id)
  const spentAfter = getSpentOrFallback(tripService.getById(created.id))
  check('expense reflected in cached summary', summaryAfter.spent === 800000 && spentAfter !== spentBefore)

  const serverSummary = await apiFetch(`/trips/${created.id}/budget/`)
  check('server budget recalculated', serverSummary.spent === 800000 && serverSummary.categories.accommodation === 800000)

  // ---- Packing (Integration Test 07) ----------------------------------
  await packingService.ensureLoaded(created.id)
  const item = await packingService.create({
    tripId: created.id,
    name: 'شارژر',
    quantity: 1,
    category: 'tech',
  })
  check('packing item created (category mapped tech→electronics)', item.category === 'tech')

  packingService.toggleDone(item.id)
  await new Promise((r) => setTimeout(r, 200))

  const progress = await apiFetch(`/trips/${created.id}/packing/progress/`)
  check('packing progress updated on server', progress.packed === 1 && progress.percentage === 100)

  // Reload-proof: refetch items and verify state persisted.
  await packingService.reload(created.id)
  const reloadedItem = packingService.getById(item.id)
  check('packed state survives reload', reloadedItem?.done === true)

  // ---- Weather + Notes + Notifications (Phases 24-26) -----------------
  const note = await notesService.create({
    tripId: created.id,
    title: 'یادداشت تست',
    content: 'محتوای یادداشت',
  })
  check('note created via API', Boolean(note.id) && !String(note.id).startsWith('temp'))

  await notesService.ensureLoaded(created.id)
  const serverNotes = await apiFetch(`/trips/${created.id}/notes/?page_size=100`)
  check('note persisted on server', (serverNotes.results?.length || 0) >= 1)

  await weatherService.ensureLoaded(created.id)
  check(
    'weather service returns list (may be empty pre-seed)',
    Array.isArray(weatherService.getForTrip(created.id)),
  )

  // ---- Cleanup + logout ----------------------------------------------
  await tripService.remove(created.id)
  await tripService.reload()
  check('deleted trip is gone on server', !tripService.list().some((t) => t.id === created.id))

  await authService.logout()
  check('tokens cleared after logout', !authService.isAuthenticated())

  let unauthorizedCaught = false
  try {
    await apiFetch('/users/me/')
  } catch (error) {
    unauthorizedCaught = error.status === 401
  }
  check('protected API returns 401 after logout', unauthorizedCaught)

  // ---- Demo account: notifications read-all --------------------------
  notificationsService.reset()
  await authService.login('demo@tripos.dev', 'Demo-Passw0rd!123')
  await notificationsService.ensureLoaded()
  const unreadBefore = notificationsService.unreadCount()
  check('demo notifications loaded', notificationsService.list().length >= 2, `got ${notificationsService.list().length}`)

  if (unreadBefore > 0) {
    await notificationsService.markAllRead()
    check('mark-all-read works', notificationsService.unreadCount() === 0)
  }

  await authService.logout()
} catch (error) {
  failures += 1
  console.error('UNEXPECTED ERROR:', error.message || error)
}

console.log(failures === 0 ? '\nALL INTEGRATION CHECKS PASSED' : `\n${failures} CHECK(S) FAILED`)
process.exit(failures === 0 ? 0 : 1)
