# Generated by Django 5.2.17 on 2026-08-26 08:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('attraction', 'Attraction'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('museum', 'Museum'), ('hotel', 'Hotel'), ('shopping', 'Shopping'), ('nature', 'Nature'), ('activity', 'Activity'), ('airport', 'Airport'), ('transport', 'Transport'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/%Y/%m/')),
                ('estimated_cost', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='trips.tripday')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='trips.trip')),
            ],
            options={
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['trip', 'day'], name='places_plac_trip_id_2b6818_idx'), models.Index(fields=['trip', 'category'], name='places_plac_trip_id_15f0ff_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='place_end_time_gt_start_time')],
            },
        ),
    ]
