# Generated by Django 5.2.17 on 2026-08-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('food', 'Food'), ('transport', 'Transport'), ('shopping', 'Shopping'), ('relaxation', 'Relaxation'), ('adventure', 'Adventure'), ('culture', 'Culture'), ('other', 'Other')], default='other', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='trips.tripday')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
    ]
