# Generated by Django 5.2.17 on 2026-08-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('places', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='places.place'),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.trip'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['trip', 'day'], name='activities__trip_id_2c6c24_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['trip', 'completed'], name='activities__trip_id_45a2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['trip', 'category'], name='activities__trip_id_77a453_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='activity_end_time_gt_start_time'),
        ),
    ]
