# Generated by Django 5.2.17 on 2026-08-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('documents', 'Documents'), ('electronics', 'Electronics'), ('personal', 'Personal'), ('health', 'Health'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_packed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='trips.trip')),
            ],
            options={
                'ordering': ('category', 'created_at'),
                'indexes': [models.Index(fields=['trip', 'is_packed'], name='packing_pac_trip_id_5c19a6_idx'), models.Index(fields=['trip', 'category'], name='packing_pac_trip_id_3657de_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='packing_quantity_gte_one')],
            },
        ),
    ]
