# Generated by Django 5.2.17 on 2026-08-26 09:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('temperature_high', models.IntegerField()),
                ('temperature_low', models.IntegerField()),
                ('condition', models.CharField(choices=[('sunny', 'Sunny'), ('partly_cloudy', 'Partly Cloudy'), ('cloudy', 'Cloudy'), ('rain', 'Rain'), ('thunderstorm', 'Thunderstorm'), ('snow', 'Snow'), ('windy', 'Windy'), ('fog', 'Fog')], default='sunny', max_length=20)),
                ('wind_speed', models.PositiveIntegerField(default=0)),
                ('humidity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('sunset', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather', to='trips.tripday')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='trips.trip')),
            ],
            options={
                'ordering': ('date',),
                'constraints': [models.UniqueConstraint(fields=('trip', 'date'), name='uniq_trip_weather_date'), models.CheckConstraint(condition=models.Q(('temperature_low__lte', models.F('temperature_high'))), name='weather_low_lte_high')],
            },
        ),
    ]
